### ISSUE TITLE
只有您一个人在翻译吗？

### ISSUE THREAD

**Issue by yuangel45** [gdut-yy/JavaScript-The-Definitive-Guide-7th-zh#2]
您是已经停止更新了吗？
看履历一直只有您一个人在进行维护，国内前端很需要这样的书呀。
今天看旧版本的书还有看不懂的地方去对比了下英文原版，好想参与进来哪怕只是给翻译者加油！！

**Comment by gdut-yy** [comment]
@yuangel45 没停止更新，只是工作太忙没时间维护罢了。欢迎参与进来的，提PR就OK了

**Comment by yuangel45** [comment]
git使用我也有点小白，我这边在查大家所说的pull request到底怎么用，不过我暂时fork过去了，并且因为最看到了函数那章，先从这章开始跟着翻译。
