### ISSUE TITLE
关于注释

### ISSUE THREAD

**Issue by yuangel45** [gdut-yy/JavaScript-The-Definitive-Guide-7th-zh#5]
大神我这里翻译到了一个原书带注释的地方，我去读第六版翻译和原版对比看到他们是这么处理的：
> 原书： 1.  2.  3.
译本： [1] [2] [3]

 这里我们也是这样处理可以吗？

**Comment by gdut-yy** [comment]
@yuangel45 
1. 2. 3. 是 markdown 语法的有序列表
经过实践，建议是加上 > 引用标记的为对应译文
印刷版和网页版有差异，可参考 oreilly 官网的原文

**Comment by yuangel45** [comment]
好的了解，感谢!
